# Generated by Django 6.0 on 2026-07-24 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(unique=True)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=12)),
                ('correct_explanation', models.TextField()),
                ('wrong_explanation', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('requires_lab', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='simulados.certificationlevel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='simulados.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='simulados.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, unique=True)),
                ('simulation_type', models.CharField(choices=[('rapido', 'Simulado rápido'), ('completo', 'Simulado completo'), ('topico', 'Por tópico'), ('revisao', 'Modo revisão'), ('laboratorio', 'Modo laboratório')], default='rapido', max_length=20)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='simulados.certificationlevel')),
                ('topics', models.ManyToManyField(blank=True, to='simulados.topic')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='simulados.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_for_review', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulados.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulados.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simulados.simulationattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('average_time_seconds', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.certificationlevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
