# Generated by Django 6.0 on 2026-07-24 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('study_topic', models.CharField(blank=True, max_length=100)),
                ('scenario', models.TextField(help_text='Cenário prático do laboratório')),
                ('task', models.TextField(blank=True, default='', help_text='O que o aluno deve fazer')),
                ('step_by_step', models.TextField(blank=True, default='', help_text='Passo a passo de execução')),
                ('explanation', models.TextField(help_text='Explicação técnica e raciocínio')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('checklist', models.TextField(blank=True, default='')),
                ('official_reference', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['mission__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('certification', models.CharField(blank=True, max_length=12)),
                ('track', models.CharField(choices=[('principal', 'Eixo principal'), ('extra', 'Missões extras')], default='principal', max_length=20)),
                ('summary', models.TextField()),
                ('objective', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('unlocked_by_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['track', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='iniciado', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='game.mission'),
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_challenges', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
